### ISSUE TITLE
Broken sort by date after last upgrade

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#1004]
### Steps to reproduce

1. Have some view where the date field is present, eg `Date of modification`
2. Set the rule in view to sort by date and check that it is working
3. Upgrade to 0.7.0
4. Open any view where sorting by date rule is present
5. Observe that the sorting is broken
6. Check sorting by ABC - observe that it is partially working apart of cyrillic letters Є, І, which goes at the end mistakenly

### Expected behavior

The sorting by date should work as expected

### Actual behavior

The sorting by date is not working at all, independently of ASC or DESC

### Tables app version

0.7.0

### Browser

Brave

### Client operating system

Win10 x64

### Operating system

Ubuntu

### Web server

Apache

### PHP engine version

PHP 8.2

### Database

MariaDB

### Additional info

I may assume that this may be related to the changes in the date format, however the Date of Modification is shown correctly.

**Comment by enjeck** [comment]
Hi @ostasevych. I'm unable to reproduce this. Can you please share a screencast of what's happening?

**Comment by ostasevych** [comment]
> Hi @ostasevych. I'm unable to reproduce this. Can you please share a screencast of what's happening?

Sadly, I cannot share screencasts, please, find the screenshots where I show how ordering (sorting) is not working by the key Last changed:
![image](https://github.com/nextcloud/tables/assets/5199030/4dbda271-1ef0-4799-a795-9b7b4cb99e5e)
![image](https://github.com/nextcloud/tables/assets/5199030/cf0d3531-4ecc-496a-8a60-a4dc2928e203)

![image](https://github.com/nextcloud/tables/assets/5199030/e2bc1b14-c65c-48de-8201-03e988f9fc50)
![image](https://github.com/nextcloud/tables/assets/5199030/c377cf66-d598-4d74-8b45-7ba6021255b0)

**Comment by ostasevych** [comment]
Update to v.0.7.1 hasn't solved the issue :(
Stil having trouble with sorting by date in views.

**Comment by ostasevych** [comment]
UPD: I suspect that the command `occ tables:legacy:transfer:rows --all` broken the data format thus the data data are no more _sortable_. Can anybody check that?
