### ISSUE TITLE
Deleting row in a shared table is not possible

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/tables#1031]
### Steps to reproduce

1. Have a table shared from user 1 to user 2
2. User 2 can now add new rows and edit existing rows

### Expected behavior

User 2 should also be able to delete rows.
I understand that this is technically a different permission, but if the user can already edit the row data they can already destroy the data in it, so not being able to delete the row directly just adds a little bit more work for a malicious actor.

### Actual behavior

Rows can not be deleted.

### Tables app version

c.nc.c

### Browser

Firefox 125.0.2

### Client operating system

Arch Linux

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

I couldn't find any existing issue about this, sorry if this is a duplicate.

**Comment by provokateurin** [comment]
I don't know, maybe that is the actual problem :D Let me ask Andy

**Comment by provokateurin** [comment]
Excuse me, this was a human error :upside_down_face:

**Comment by blizzz** [comment]
Layer 8 is toughest ;)
