### ISSUE TITLE
Missing localisation for strings "Share with accounts" and "User..."

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#1040]
I've found missing localisation for strings in the window of creating an app, see on the screenshot underlined in red:

![image](https://github.com/nextcloud/tables/assets/5199030/6db9afe1-8511-40fb-878e-c3f50f69d522)

### Tables app version

v.0.7.1

**Comment by blizzz** [comment]
The strings are all translatable, what is missing are translations. They can be contributed at https://github.com/nextcloud/tables/pull/1041
