### ISSUE TITLE
Cannot insert row after upgrade to 0.7

### ISSUE THREAD

**Issue by enjunear** [nextcloud/tables#1058]
### Steps to reproduce

1. Upgrade to v0.7.0 or 0.7.1
2. Bang your head with issues #998 and #999
3. Fix 998/999 by running `occ tables:legacy:transfer:rows --all`
4. Reboot server
5. Wife complains because she can't insert a new row into an existing table
6. Try myself, confirm problem.

Dig into the console for an error message:
Axios error > response.data.message: 'OCA\\Tables\\Service\\RowService - create: An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "oc_tables_row_sleeves_pkey"\nDETAIL:  Key (id)=(8) already exists.'

### Expected behavior

Row inserts normally without errors or complaints.

### Actual behavior

Wife complained.

### Tables app version

0.7.1

### Browser

Firefox 125.0.3

### Client operating system

Windows 10

### Operating system

Linux 5.15.0-105-generic x86_64

### Web server

Nginx

### PHP engine version

PHP 8.2

### Database

PostgreSQL

### Additional info

All running in docker swarm

**Comment by enjunear** [comment]
May be related to #1029

**Comment by blizzz** [comment]
Yes, dup of #1029
