### ISSUE TITLE
Creating an application doesn't work

### ISSUE THREAD

**Issue by oculos** [nextcloud/tables#1060]
### Steps to reproduce

1. A normal user (ie, not an admin) attempt to create an application
2. An error is shown "Can't create application"

### Expected behavior

That an application could be created

### Actual behavior

<img width="418" alt="Screenshot 2024-05-05 at 07 45 54" src="https://github.com/nextcloud/tables/assets/6791923/e3c6e93b-90d5-4f00-8644-d90e052d0d58">

### Tables app version

0.7.1

### Browser

Safari

### Client operating system

Mac

### Operating system

linux

### Web server

Nginx

### PHP engine version

PHP 8.2

### Database

MariaDB

**Comment by MyPsyOnline** [comment]
I had the same error

i was finaly able to create application by changing the emoji icon during the creation process

**Comment by enjeck** [comment]
@oculos @MyPsyOnline We have a new release that should fix this. Please update and report back if this issue persists

**Comment by enjeck** [comment]
> @enjeck it was not backported for 0.7.1, we need a new release.

whoops okay

**Comment by xbluemonkx** [comment]
this is a duplicate of this https://github.com/nextcloud/tables/issues/1007

**Comment by blizzz** [comment]
closing as dup
