### ISSUE TITLE
Submit row details with ctrl+enter

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/tables#1064]
### Is your feature request related to a problem? Please describe.

As a Tables user I want to quickly save my changes when editing a row. Currently I have to tab to the *Save* button or use the mouse.

### Describe the solution you'd like

Convert the row editor modal to a native HTML form I can submit using ctrl+enter when an input is focused.

**Comment by juliushaertl** [comment]
We should also make sure this works on all modals (table/view/application/row create/edit)
