### ISSUE TITLE
No error handling for MIME type check during import

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/tables#1067]
### Steps to reproduce

1. Create a table
2. Select a local text file for import

### Expected behavior

Import dialog shows an error

### Actual behavior

Import appears to take forever. Error is logged.

![Bildschirmfoto vom 2024-05-06 11-16-39](https://github.com/nextcloud/tables/assets/1374172/810cca66-a35d-46a1-83df-8055f58d138e)
![Bildschirmfoto vom 2024-05-06 11-16-43](https://github.com/nextcloud/tables/assets/1374172/1a3ba73f-3398-49b2-984c-be3558e4169c)

### Web server

None

### PHP engine version

None

### Database

None

**Comment by juliushaertl** [comment]
We should probably also accept text/plain if that is what a csv ends up with.

**Comment by luka-nextcloud** [comment]
@ChristophWurst I cannot reproduce the problem, could you please share the file you tested?

**Comment by ChristophWurst** [comment]
Shared privately

**Comment by luka-nextcloud** [comment]
I can reproduce now, thanks.
