### ISSUE TITLE
Provide OCS endpoints for creating rows in Tables or Views

### ISSUE THREAD

**Issue by blizzz** [nextcloud/tables#1105]
### Is your feature request related to a problem? Please describe.

Turn the legacy `api1#createRowInView` and `api1#createRowInTable` endpoints into OCS endpoints, so that they are easier usable for third parties.

### Describe the solution you'd like

Evaluate whether it is possible to combine them into one endpoint. 

### Additional context

This is required for the upcoming workflow engine efforts.

**Comment by juliushaertl** [comment]
@blizzz Could you line this up for the next two weeks? I would expect implementation being rather just reusing existing services and writing tests.
