### ISSUE TITLE
Stray contexts endpoints - keep, sunset, remove?

### ISSUE THREAD

**Issue by blizzz** [nextcloud/tables#1123]
In `ContextController` we have the methods `removeNode` and `addNode`, which are – to my knowledge – unused. In the frontend `update` is used instead. 

Imho that makes them candidates for removal.

However, we have released 0.7 already with those APIs.

Simply removing them now is not great, there *might* be unknown usages externally already.

One option is to keep and maintain them, the other to sunset them with a deprecation notice and remove them at a later point. What do you think? @enjeck @juliushaertl

**Comment by enjeck** [comment]
> Simply removing them now is not great, there _might_ be unknown usages externally already.

I say we remove them, since its extremely unlikely that there are external usages already

**Comment by juliushaertl** [comment]
Yep, agreed.
