### ISSUE TITLE
Share Application with groups

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/tables#1128]
### Is your feature request related to a problem? Please describe.

At the moment you can only share Applications with Users.

### Describe the solution you'd like

I would like to bae able to share it with user-groups too.

### Describe alternatives you've considered

I do not have a valid workaround except adding all the users manually, but what if i have to share it with 40 people that are all in the same group? and what if another person is added to or one person is removed from that group. i have to manually track this in the tables application. that is not very handy.

**Comment by blizzz** [comment]
I think it just needs a UI picker for groups, and maybe a little glue around. 

You can share already via API, and groups shared with are actually visible in the web interface. 

So, workaround:

```
curl \
  -X POST \
  -u LOGIN:APPTOKEN \ 
  --json '{"nodeId": CONTEXT_ID, "nodeType": "context", "receiver": "GROUP_ID", "receiverType": "group"}' \
  https://cloud.example.com/index.php/apps/tables/api/1/shares
```

replace `LOGIN`, `APPTOKEN`, `CONTEXT_ID`, `GROUP_ID` accordingly.

The groups also survived a change in the share recipients later on.

cc @enjeck
