### ISSUE TITLE
Undefined array key "manageTable" at ViewService.php#419

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/tables#1131]
### Steps to reproduce

- `GET /apps/tables/view`

### Expected behavior

Nothing in the logs

### Actual behavior

Undefined array key "manageTable" at …/apps/tables/lib/Service/ViewService.php#419

### Tables app version

0.7.2

**Comment by Jednadvacet** [comment]
Same to me.

**Comment by blizzz** [comment]
There is another code path that still leads to this error

![Screenshot_20240613_111855](https://github.com/nextcloud/tables/assets/2184312/ab101aa9-ca26-4ec1-91fd-e1c0729a0eac)
