### ISSUE TITLE
Link of the App-Symbol doesn't work

### ISSUE THREAD

**Issue by cablesky** [nextcloud/tables#1138]
### Steps to reproduce

1. Click on the App Symbol
2.
3.

### Expected behavior

The link from the app icon doesn't work. When I click on the table symbol, the current page is reloaded - but no web interface for the app appears.

### Actual behavior

The current page is reloaded.

### Tables app version

latest

### Browser

Chrome

### Client operating system

Windows

### Operating system

Ubuntu 

### Web server

Nginx

### PHP engine version

PHP 8.1

### Database

MySQL

**Comment by blizzz** [comment]
@cablesky So, you are on the web interface, already in the tables app, and click the icon again. The page reloads, but you do not see content? Please be precise in the description. Did you check you nextcloud.log? Which version of tables do you run?

**Comment by cablesky** [comment]
@blizzz 
![table_error](https://github.com/nextcloud/tables/assets/28872858/83700c67-ecb2-4e3d-91e9-a23f2a4d85b2)
Attached is a video. I checked the nextcloud.log - unfortunately nothing is logged there. 
I am using version 0.7.3.

**Comment by cablesky** [comment]
Ok, i found the solution: When i deactivate the full text search, the app works fine.. Very strange...

**Comment by blizzz** [comment]
Alright, could you then check your browser console? Does it perhaps show errors?

**Comment by cablesky** [comment]
too soon to celebrate. As soon as the full-text search index has been created, the old problem occurs again and the icon on the menu bar reloads when you click on it. Since the "Tasks icon" next to the "Tables" icon has the same problem, I don't think this is a problem with Tables...

**Comment by cablesky** [comment]
here the issue from fulltextsearch: https://github.com/nextcloud/fulltextsearch/issues/842

**Comment by enjeck** [comment]
Since this is not a Tables problem, we can close this. Feel free to reopen if it is.
