### ISSUE TITLE
Fixed Default Values per View

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/tables#1140]
### Is your feature request related to a problem? Please describe.

Hi,
let us assume we have an table that is called "Vacations". And this table has four columns: Employee, Start, End, Status.

Furthermore Status is a dropdown list that has three values: New, Approved, Declined.

Now I create a application where employees can add new rows to the table. In this application the status should allways be "New".

Is there an option to set a default value per application or per view?

Another scenario: We could have a Article Master Data table. The table has a department column with values "Department A" and "Department B". Now i create two views. One with only articles of Department A and one with only Articles of Department B. - If i use those in an application I want to make sure, that new lines for each view have a non-changeable value for the department column. Depending in which view the new line is added.

**Comment by blizzz** [comment]
@juliushaertl i think we talked about this at some point, but I don't think/see that there was a similar issue raised yet

**Comment by juliushaertl** [comment]
Kind of overlaps with https://github.com/nextcloud/tables/issues/638

**Comment by blizzz** [comment]
> Kind of overlaps with #638

Yes, this one. I'd consider it a duplicate actually.
