### ISSUE TITLE
OpenAPI annotation for createRowInTable is likely wrong

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/tables#1157]
### Steps to reproduce

See https://github.com/nextcloud/tables/blob/main/lib/Controller/Api1Controller.php#L1100

### Expected behavior

The code seems to expect

```php
/** @var array<int,mixed> */
```

### Actual behavior

Actually declared is

```php
/** @var array{columnId: int, value: mixed} */
```

### Tables app version

main

### Web server

None

### PHP engine version

None

### Database

None

**Comment by blizzz** [comment]
`<mixed, array{'columnId': int, 'value': mixed}>` to  be more precise.
