### ISSUE TITLE
Unable to get back previously set (github) link

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/tables#1186]
### Steps to reproduce

1. Add a column for github links
2. Enter a github link
3. Save
4. Open the row
5. Try to read/copy the github link

### Expected behavior

I can

### Actual behavior

I cant

![image](https://github.com/nextcloud/tables/assets/1374172/df76bd6c-343d-4639-95a2-cadf43d2a4f0)

### Web server

None

### PHP engine version

None

### Database

None

**Comment by juliushaertl** [comment]
In addition to fix the styling issue we should probably add two buttons to open the link and to copy it. Otherwise there is also #787 but this would only be helping for links that are not using the search result multiselect
