### ISSUE TITLE
Navigation table entries UI issues

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/tables#1191]
The app navigation has a few small quirks with the new UI adjustments:

- [ ] The counter (3 rows) is cut off, we should probably just use the number as it is done in other apps without the word rows
- [ ] text and icon color is inconsistent in dark mode (should use the proper css var for text on primary)

![image](https://github.com/user-attachments/assets/a106f4e4-ade1-4dcd-8475-17975d3798be)

![image](https://github.com/nextcloud/tables/assets/3404133/9e36cf60-369f-44b9-ac40-c73ef1bf0ab3)

**Comment by enjeck** [comment]
@juliushaertl 

> we should probably just use the number as it is done in other apps without the word rows

What other apps are doing it this way? I don't think it'll be obvious to users what the number is without explicitly mentioning 'rows'.

**Comment by juliushaertl** [comment]
We generally use it as counter for whatever entries are listed in those navigation entries, some examples would be mail, contacts, notes, talk, all without a label on what the counter is:

<img width="329" alt="Screenshot 2024-07-15 at 11 47 18" src="https://github.com/user-attachments/assets/100392d9-dae0-4040-8c94-46fd5d5154d9">
<img width="335" alt="Screenshot 2024-07-15 at 11 46 52" src="https://github.com/user-attachments/assets/b0ee58fe-71bf-489f-98cf-9bac5b19ce8f">
<img width="322" alt="Screenshot 2024-07-15 at 11 47 05" src="https://github.com/user-attachments/assets/731d1aca-8ac1-415f-9a88-d64cb22df648">
<img width="331" alt="Screenshot 2024-07-15 at 11 48 52" src="https://github.com/user-attachments/assets/c68a2552-0700-4454-9fe9-70f7d57a90c3">
