### ISSUE TITLE
Undefined array key "manageTable"

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#1225]
### Steps to reproduce

1. Share a table view with some user
2. In sharing options select "Can manage view"
3. Observe pop-up errors and the log record:
```
[PHP] Error: Undefined array key "manageTable" at /var/www/html/nextcloud/apps/tables/lib/Service/ViewService.php#419
	GET /apps/tables/view
```

### Expected behavior

Should be ok, when sharing the view with other users

### Actual behavior

Sharing a view with other users when selected "Can manage the view" leads to errors.

### Tables app version

0.7.4

### Browser

Brave Version 1.67.134

### Client operating system

Windows 10 x64

### Operating system

Ubuntu 22.04

### Web server

Apache

### PHP engine version

PHP 8.2

### Database

MariaDB

**Comment by blizzz** [comment]
Fixed with https://github.com/nextcloud/tables/pull/1173, but not released yet (backport pending)
