### ISSUE TITLE
Richtext "expand" icon is misaligned in modals

### ISSUE THREAD

**Issue by enjeck** [nextcloud/tables#1226]
For example, in the "Edit row" modal

![Screenshot from 2024-07-22 08-31-18](https://github.com/user-attachments/assets/d9d3558c-f17b-431c-976f-7b3f3ad8bff0)

**Comment by juliushaertl** [comment]
@JuliaKirschenheuter As you're looking into UI fixes right now anyways, I don't recall if this was listed in the design review tasks already?

**Comment by JuliaKirschenheuter** [comment]
@enjeck should it be here or closed to "How to do"?

![Screenshot from 2024-07-24 11-49-26](https://github.com/user-attachments/assets/6ea6b8c9-dad9-44e1-a0fc-aba30a6e863c)

**Comment by juliushaertl** [comment]
Looks good as shown in the screenshot 👍
