### ISSUE TITLE
 Undefined table: 7 ERROR:  relation "oc_tables_row_cells_usergroup" does not exist

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/tables#1256]
### Steps to reproduce

After creating a new table and reloading the page:

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/8433d831-4379-4976-82db-1bb0b2c2ce4d">

```
{
    "message": "OCA\\Tables\\Db\\Row2Mapper - getRows: An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"oc_tables_row_cells_usergroup\" does not exist\nLINE 1: ..., CAST(\"value_type\" AS TEXT) AS \"value_type\" FROM \"oc_tables...\n                                                             ^"
}
```

ReqId gEUV73pIp1e8rzzwAlMQ

**Comment by juliushaertl** [comment]
Where did this happen? We should not have released the code in question yet

**Comment by juliushaertl** [comment]
Ah daily, we did not bump the app version so the migration didn't execute.

**Comment by juliushaertl** [comment]
Let me fix that manually there, planned to build a new release tomorrow.

**Comment by juliushaertl** [comment]
Should be working now again there, could you verify?

**Comment by SystemKeeper** [comment]
Yes, works fine now, thanks!
