### ISSUE TITLE
TypeError: this.$el.querySelector is not a function

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/tables#1257]
### Steps to reproduce

1. Create a new table
2. Click on "Create row"
3. Close the dialog again

Tested on daily.

### Expected behavior

No error

### Actual behavior

<img width="1210" alt="image" src="https://github.com/user-attachments/assets/232ad750-95e4-437a-87be-07058f7a6e91">

### Web server

None

### PHP engine version

None

### Database

None

**Comment by juliushaertl** [comment]
Fix added to #1259
