### ISSUE TITLE
Ability to clone row

### ISSUE THREAD

**Issue by baditaflorin** [nextcloud/tables#1266]
### Is your feature request related to a problem? Please describe.

Let's say I created a row entry, and I want to create another copy of that row and ust modify one or 2 values, currently I need to create a new row and add all the data again, even in some use-cases I would need just to change the value of a single column

### Describe the solution you'd like

When selecting a row, have a duplicate feature that will duplicate the row.

**Comment by juliushaertl** [comment]
Closing as a duplicate of https://github.com/nextcloud/tables/issues/69
