### ISSUE TITLE
Add ability to add Expression Columns

### ISSUE THREAD

**Issue by baditaflorin** [nextcloud/tables#1270]
### Is your feature request related to a problem? Please describe.

Example, I have 2 columns, a StartDate and a EndDate. I want to create a new column that will calculate the time difference between EndDate - StartDate to calculate the amount of time it took for that specific entry.

Or if you would have 2 itnerege columns, you would want to perform some mathematical expression on a third column that would be like divide column A / B

**Comment by juliushaertl** [comment]
I'd consider this as a duplicate of https://github.com/nextcloud/tables/issues/888 Maybe you can leave a comment there about the use case with adtes
