### ISSUE TITLE
Add a picker for users

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/tables#1275]
### Is your feature request related to a problem? Please describe.

I am attempting to utilize nextcloud tables application to create an application for "driving requests"

in a nutshell the company has a car fleet, and users can request a car to use for doing their work.

more often than not they drive out with a colleague, so they have to mention this as well

### Describe the solution you'd like

I would like to add a picker so that they can select eligible colleagues from a drop down.
eligible would mean users that have access to the application

### Describe alternatives you've considered

manually add users in a dropdown, this would mean i would need to manage this list manually

**Comment by juliushaertl** [comment]
Already merged for the next release #586

**Comment by Fuseteam** [comment]
oh cool~ looking forward to it
