### ISSUE TITLE
Link whole Cospend Projekt

### ISSUE THREAD

**Issue by tatrapikao** [nextcloud/tables#1360]
### Steps to reproduce

At the Moment Columns type "Link" has the option "Cospend". It only enables me to link a transaction but not a whole project - would be nice to be able to do that.

### Expected behavior

type a string and be presented with corresponding Cospend-Projects in addition to Cospend-Transactions.

### Actual behavior

only show Transactions matching the typed string.

### Web server

None

### PHP engine version

None

### Database

None

**Comment by juliushaertl** [comment]
FYI @julien-nc 

The link column is based on reference providers and unified search so nothing we can fix on the tables side, but cospend would need to provide a unified search result for projects.
