### ISSUE TITLE
Can't add myself in Users or Groups column

### ISSUE THREAD

**Issue by poiNt3D** [nextcloud/tables#1361]
### Steps to reproduce

1. Create a column with "users or groups" type
2. Type your name
3. Nothing is found

### Expected behavior

You should be able to select any users

### Actual behavior

You can't find your own account

### Tables app version

0.8.0

### Browser

Firefox

### Client operating system

Windows

### Operating system

Ubuntu

### Web server

Apache

### PHP engine version

PHP 8.3

### Database

PostgreSQL

### Additional info

Nextcloud 30

**Comment by lars-becker** [comment]
This is a dupe of #1355.

**Comment by poiNt3D** [comment]
Duplicate
