### ISSUE TITLE
Make a column read only ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [nextcloud/tables#1415]
### Is your feature request related to a problem? Please describe.

I am using tables for tracking the progress of our cooperative members.
We have a lot of column to handle.
I want to organize it visually to facilitate the use of it.
I want to describe group of colomns with chapters title when creating a new line.
I am using rich text field with default values to do that actually, but people could change the default value.

### Describe the solution you'd like

As a creator of the table could it be possible to make this "title chapter text column" readonly
Maybe it could be just a text zone in markdown between columns ?

### Describe alternatives you've considered

I don't see any, but maybe someone could help me?

**Comment by Aveyron-RetD** [comment]
similar to #1154

**Comment by blizzz** [comment]
> similar to [#1154](https://github.com/nextcloud/tables/issues/1154)

Thanks for linking it. I would call it a duplicate – I tuned this title there a bit and close this one as duplicate.
