### ISSUE TITLE
usergroupDefault is not a valid attribute

### ISSUE THREAD

**Issue by maghog** [nextcloud/tables#1420]
### Steps to reproduce

Upgrade from Tables v0.7.5 to v0.8.1

After upgrade no Tables are shown in web interface.

Log error: 
An internal error or exception occurred: usergroupDefault is not a valid attribute

[tables] Varning: An internal error or exception occurred: usergroupDefault is not a valid attribute
    GET /nextcloud/index.php/apps/tables/view/9

Running: occ tables:legacy:transfer:rows --all

-- Start transfer for table 3 (Loggbok) [1/5]
---- Found 4 columns
---- Found 70 rows
⚠️  Could not transfer data. Continue with next table. The logs will have more information about the error: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '96' for key 'PRIMARY'

### Expected behavior

All existing tables should be available and work as expected.

### Actual behavior

No tables available, see error

### Tables app version

0.8.1

### Operating system

Ubuntu 22.04 Nextcloud 29.0.8

### Web server

Apache

### PHP engine version

PHP 8.1

### Database

MariaDB

**Comment by blizzz** [comment]
Hi @maghog, thank you for the report.

>  An internal error or exception occurred: usergroupDefault is not a valid attribute

Where do you see this one? In the browser console or nextcloud.log? If nextcloud.log, during upgrade or anytime you open the tables app?

> -- Start transfer for table 3 (Loggbok) [1/5]
---- Found 4 columns
---- Found 70 rows
⚠️ Could not transfer data. Continue with next table. The logs will have more information about the error: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '96' for key 'PRIMARY'

The error only happens for the mentioned table?

**Comment by maghog** [comment]
Hi Arthur,

Where do you see this one? In the browser console or nextcloud.log? If nextcloud.log, during upgrade or anytime you open the tables app?
- In nextcloud.log when open tables app

The error only happens for the mentioned table?
- No all tables, this was only an example. After upgrade I have no working tables.

**Comment by maghog** [comment]
Hi @blizzz 

Any idea how i can proceed to solve the problem?

**Comment by blizzz** [comment]
Hi @maghog! I need to have a closer look and allocate time for it. I have been OOTO for the last two weeks, thus the delay.

Generally, it seems there are two issues here: on around the usergroup field, the other about the migration. 

Maybe @enjeck knows something on the `usergroupDefault is not a valid attribute`?

**Comment by maghog** [comment]
Upgrade to 0.8.2 and running occ db:add-missing-indices solved this issue.
