### ISSUE TITLE
Favorites is broken

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/tables#1469]
### Steps to reproduce

1. Open tables
2. Remove and add favorites
3. Reload the page

### Expected behavior

Favorites reflects what you added and removed

### Actual behavior

Favorites are back to default ('tutorial')

### Tables app version

latest on cloud.nc.com

### Browser

Firefox 132.1 and Safari

### Client operating system

Linux and Mac OS

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

As of 21/11/2024 cloud.nextcloud.com runs 30.0.2.2

**Comment by blizzz** [comment]
dup of #1350
