### ISSUE TITLE
Add modification of the field type where possible

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#1497]
### Is your feature request related to a problem? Please describe.

Using the created tables authors, like me, may experience the necessity to change the type of fields, which have been created earlier, eg the fields need adding more data than initially expected.

Please, consider adding the function of chaning the type of fields, where possible, eg _one row text_ to a _text area_. There may be other type pairs of what could be modified.

### Describe the solution you'd like

A user can go to the field, click edit it and change the type to the one which is allowed. 

There should be foreseen a warning about consequences for the field type changes if any, eg, if I change from text area to the text row, what may lead to cutting the text in records to a certain number of symbols. In this case, either not to allow potentially dangerous operations, or show warning about the results of the operation to be done.

### Describe alternatives you've considered

In order to mitigate some potentially dangerous consequences on the already existing data in records, let the field type modification operation undertake only in CLI mode.

**Comment by blizzz** [comment]
Thanks for the suggestion, @ostasevych. It was already filed as https://github.com/nextcloud/tables/issues/485 hence closing as dup.

**Comment by blizzz** [comment]
P.S.: Please add your thumbs-up reaction in the other ticket, to indicate the interest in the feature request.
