### ISSUE TITLE
Bug: line break after checkbox in long text

### ISSUE THREAD

**Issue by jonknud** [nextcloud/tables#207]
I just updated to Nextcloud 25 and also tried Nextcloud 26.

If I use a long text column and add a checkbox it will be rendered with a line break after the check box

![image](https://user-images.githubusercontent.com/28842347/230894310-f3d76532-1c56-4686-819a-093101963a36.png)

In Nextcloud 24 the text (in this case "ss") was behind the checkbox.

**Comment by juliushaertl** [comment]
Fixed by #247
