### ISSUE TITLE
What is Bestellungsgewicht?

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/tables#229]
When creating a new column there is a setting "Bestellungsgewicht". I can't find any explanation for this.
![Bestellungsgewicht](https://user-images.githubusercontent.com/28782306/232218414-c3f78b61-c037-41cd-8316-a44d5ae8e4e0.PNG)

**Comment by stefan-niedermann** [comment]
It's a bad translation for `order weight` and means priority weight - "Gewichtung in der Reihenfolge".

cc @rakekniven maybe you have a better idea?

**Comment by xbluemonkx** [comment]
ah I see. I guess the clean solution would be to have a list of columns that can be ordered using drag and drop.

Maybe a better translation would be "Spaltenposition"

**Comment by stefan-niedermann** [comment]
> I guess the clean solution would be to have a list of columns that can be ordered using drag and drop.

I guess that's a separate feature request (would you mind opening an issue for that?), that can be built on top of the order weight property (and hide the order weight property eventually.

Let's keep this issue for a better translation and a quick solution.

It actually is not a `position` as there can two columns have the same weight (i think) and there can be gaps between the position. It is not a linear counting number, so technically "Spaltenposition" is a wrong translation.

However I guess most people will understand better what "Spaltenposition" means than the current (completely wrong) term.

**Comment by xbluemonkx** [comment]
Yes i already thought that "position" is not technically correct. - Maybe it will become correct, if the "fixed order"-feature gets implemented (New ticket: https://github.com/nextcloud/tables/issues/230)
