### ISSUE TITLE
Default value is removed when adding items in a row

### ISSUE THREAD

**Issue by connium** [nextcloud/tables#235]
Adding multiple rows with "add more" enabled, default values get removed.

**Steps to reproduce the behavior**

1. Create a column with type "single line of text" for a table and set a default value (e.g. "Germany").
2. Click on the button to create a new row in the table. The input field for the column is prefilled with the default value "Germany".
3. Activate the "Add more" button.
4. Save the row. The modal will be cleared to allow adding another row.
5. This time the input field for the column is not prefilled but empty.

**Expected behavior**

The input field for the column should be pre-filled each time.

**Environment**

- Nextcloud version: 25.0.5
- Tables version: 0.4.0

**Comment by juliushaertl** [comment]
Seems fixed on main, will close
