### ISSUE TITLE
CSV download not possible

### ISSUE THREAD

**Issue by connium** [nextcloud/tables#237]
When trying to download a table as csv file, nothing happens after clicking on the download button.

**Steps to reproduce the behavior**

1. In a table with some data (e.g. the tutorial table) click on "download as csv" from the menu.
2. Nothing happens.

**Expected behavior**

A file download will start.

**Additional information**

In the browser console the following error occurs:

```
TypeError: this[n] is not a function
    getValueByColumnType exportTableMixin.js:37
    downloadCsv exportTableMixin.js:21
    downloadCsv exportTableMixin.js:18
    downloadCsv exportTableMixin.js:14
    csv NcTable.vue:1
    VueJS 4
    csv CustomTable.vue:1
    VueJS 4
    downloadCSV TableHeader.vue:91
    VueJS 4
    onClick index.module.js:2
    VueJS 3
vue.runtime.esm.js:3049:8
```

**Environment**

- Nextcloud version: 25.0.5
- Tables version: 0.4.0
- Browser: Firefox 112.0.1
- Client OS: Ubuntu

**Comment by juliushaertl** [comment]
@datenangebot Looks like this can also be closed with the fix in #243
