### ISSUE TITLE
vertical column lines

### ISSUE THREAD

**Issue by koebi80** [nextcloud/tables#258]
### Is your feature request related to a problem? Please describe.

Sometimes it is a bit difficult to see which values belong to which column.

![Bildschirmfoto 2023-04-28 um 14 05 43](https://user-images.githubusercontent.com/106907779/235143460-ceafe9e8-04dd-4304-a3f5-175ed26a3a5a.png)

### Describe the solution you'd like

It would be great if the table show vertical column lines.

**Comment by enjeck** [comment]
Closing this since we can consider it under https://github.com/nextcloud/tables/issues/360

**Comment by juliushaertl** [comment]
I'd say it is something different, more a general UI question.

Calling @nextcloud/designers for feedback

**Comment by juliushaertl** [comment]
Not really, just tried and that looks indeed much more readable. Besides that I'd also suggest to increase the border color from `--color-border` to `--color-border-dark` to make them a bit more visible.

**Comment by jancborchardt** [comment]
@juliushaertl sounds good to implement! :)
