### ISSUE TITLE
Fix header of the table

### ISSUE THREAD

**Issue by koebi80** [nextcloud/tables#259]
### Is your feature request related to a problem? Please describe.

For large tables, the title bar disappears when scrolling down.

![Bildschirmfoto 2023-04-28 um 14 10 49](https://user-images.githubusercontent.com/106907779/235144301-c351d36a-0888-4a22-885d-67d9b9b99954.png)

### Describe the solution you'd like

Please fix the header of the table.

**Comment by enjeck** [comment]
Should no longer be a problem after https://github.com/nextcloud/tables/pull/786
