### ISSUE TITLE
Mass Update Support

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/tables#373]
### Is your feature request related to a problem? Please describe.

It is not possible to mass update 1 column cross multiple lines based on a certain criteria. For instance I would like to update the column process from "in process" to "done" for all lines which contain in the column "person" the name Peter.

**Comment by enjeck** [comment]
Related: https://github.com/nextcloud/tables/issues/61

**Comment by quentinDupont** [comment]
Should be closed as it is same issue than #61 :)
