### ISSUE TITLE
Make the rows directly editable

### ISSUE THREAD

**Issue by AubinF** [nextcloud/tables#376]
### Is your feature request related to a problem? Please describe.

I am always frustrated when I want to modify the contents of a row, and I have to click the pencil ✎ button. I think it is slow and cumbersome.

### Describe the solution you'd like

I think clicking on a cell should be enough in order to modify its contents. I believe using the app would be much more straightforward with this feature. 

If users are afraid they might modify the contents of a row by mistake, perhaps a "lock" button could be added ?

**Comment by stefan-niedermann** [comment]
Duplicate of https://github.com/nextcloud/tables/issues/364 ?

**Comment by AubinF** [comment]
Looks like it, yes. Thanks @stefan-niedermann

**Comment by AubinF** [comment]
duplicate of #364
