### ISSUE TITLE
`columns` vs `column` (docs vs implementation)

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/tables#383]
### Steps to reproduce

According to [the docs](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/nextcloud/tables/master/APIv1.yaml#/) the endpoint for column resources is `/column/{columnId}`. All the endpoints return `HTTP 405 Method not allowed`.

It took some time, but I found out that according to the actual implementation, the column resource endpoints are `columns/{columndId}` (pay attention to the **s** of column**s**).

### Expected behavior

Documentation and implementation must be the same. I recommend updating the documentation rather than the implementation.

### Actual behavior

It's different and a bit confusing :smile: 

### Web server

None

### PHP engine version

None

### Database

None

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/tables/pull/691
