### ISSUE TITLE
View: Use basis views instead of tables

### ISSUE THREAD

**Issue by Hephi2** [nextcloud/tables#393]
### Is your feature request related to a problem? Please describe.

Use tables only as intern object but represent data only using views. This allows to enable persistent sorting in the table as well

### Describe the solution you'd like

Instead of tables, display a basis view, that contains all data (Filtering should not be consistent, only enabled in frontend)
Allow only sorting and ording of the columns of this view
All views regarding the table of the basis view should be displayed in a dropdown menu below the basis view in the navigation.

**Comment by xbluemonkx** [comment]
I think this is a very good idea, because it provides a very very clean structure: table = data (backend); views = user interaction (frontend)
