### ISSUE TITLE
View: Design Improvements

### ISSUE THREAD

**Issue by Hephi2** [nextcloud/tables#419]
### Is your feature request related to a problem? Please describe.

The following aspects were discussed in a design review call from the 18.07.2023:

### Edit View Modal

- [x] The edit view button in the navigation should open the full edit view modal and not only the edit title modal
- [x] The edit view button in the view page should not be "hidden" in a menu but visible with text next to the title. At the same time this replaces the edit title button that is currently there
Within the edit view modal:
- [x] The save button should be sticky 
- [x] The icon to indicate that the columns are movable should be the one with the two lines
- [x] Additionally there sohuld be arrow buttons to change the columnorder for keyboard accessbility as in the following example:
![image](https://github.com/nextcloud/tables/assets/46924014/80e9feb2-6414-4d8d-b417-6182a3aaaefa)
- [x] "Meta Data" should be written as "Metadata"

### Column Header Menu

- [x] The "Manage column" buttons should be buttons with an icon and a text in a list
- [x] For filtering there should be a two-level menu similar to Github or Nextcloud Mail. The first level should present what is shown here and the selected content, e.g.: Operator: Contains. When clicking on that button, this opens the second level. There you can choose between the values. For the search field value he second level provides a text field to enter a custom search string and all the possible magic values

### Shares & Sidebar

- [x] Don't show to much meta info for columns and shares. The "last edit" information is enough and should be displayed as a subline. The rest could be hidden and only shown in a debugging scenario
- [x] Change "Add Manage table" button text to "Promote to table manager" and use the crown icon as in talk
- [x] Replace "Add new share" by "Share with accounts or groups"
- [x] Replace table manager info text in views by "Open main table to adjust table management permissions"
- [x] Show the table managers inline with the other shares and add an indicator that the person is table manager
- [ ] Integrations tab can go on right of sharing
- [x] API URL can be in an input field with a copy button (similar to Files settings WebDAV URL)

### Other enhancements
- [x] Replace "Clone view" by "Duplicate view"
- [x] Creating a new view should also open the full modal not only the field for selecting the emoji and the title
- [x] Show an indicator for views that have been filtered, that not all entries are visible
- [x] Extend the template to include the views as well, e.g. for the vacation requests workflow
- [x] For Metadata column ID use "ID" instead of "Id"
- [x] For views that are shared with only create permissions, allow users to temporary view their newly created entries

**Comment by Hephi2** [comment]
It seems like I can't swap the positions of Sharing and Integration since the NcAppSidebar component seems to order the tabs alphabetically by their names...

**Comment by juliushaertl** [comment]
Let's maybe open a separate issue if that is expected or if custom order shall be possible in https://github.com/nextcloud/nextcloud-vue
