### ISSUE TITLE
Consider different sorting or way of organizing the navigation

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/tables#469]
A few points we should discuss that came up in the feature review:

- For most users shared views might be the most important ones
- Shared views probably should also be grouped by table name (or have some indication), otherwise they just show "My request" but more useful would be "Vacation requests > My requests"
- Favorites might be useful
- Archiving tables or views might be useful

**Comment by juliushaertl** [comment]
@marcoambrosini The issue description was mainly from input I received in a call, happy to have a short sync call if it helps to further clarify what we need for this one.

**Comment by marcoambrosini** [comment]
Hi all,

Taking into account the discussion with @juliushaertl, I think we can tackle this with 3 improvements

* Add ability to add favorites
favorite section on the top, with the option to add to favorite and remove from favorite in the navigation menu of each table.

* Order tables by last modified

* Add ability to archive tables. 
For this, we should probably add a collapsible navigation element and the ability to archive and archive from the same menu in the navigation

Here's a quick mockup that shows how this would look. Please let me know your thoughts



![Image](https://github.com/nextcloud/tables/assets/26852655/5ee25123-e677-477e-b2ac-b667160573b8)

**Comment by marcoambrosini** [comment]
Sounds good @juliushaertl, so you would also remove the archive?

**Comment by juliushaertl** [comment]
I'd say archived still makes sense to hide them by default.

**Comment by marcoambrosini** [comment]
Ok, fine by me with removing the captions, adding the favorites and change the sorting

**Comment by juliushaertl** [comment]
Plan for the implementation with @elzody later today:

- Backend
  - [ ] Adjust database layout
    - [ ] Add archived flag to tables and views
    - [ ] Add favorites table that stores if a node (table/view) is favorited by a user
  - [ ] Expose archived flag as an option to set through existing API endpoints when updating tables/views
  - [ ] Add Controller and Favorite service to mark as favorite and remove favorite
- Frontend
  - [ ] Navigation
    - [ ] Remove categories from navigation and just show a plain list (sort favorites first, then by last modification time)
    - [ ] Hide archived tables/views in a collapsible entry (like in deck)
  - [ ] Archiving
    - [ ] Add button to archive/unarchive in the edit table and edit view dialogs
  - [ ] Favorites
    - [ ] Add action to the menu to mark as favorite and remove from favorites
