### ISSUE TITLE
Could not load shared views. Resource not found.

### ISSUE THREAD

**Issue by alphasixtyfive** [nextcloud/tables#571]
### Steps to reproduce

1. Update to version 0.6.0
2. Try top open any tables created in previous version

### Expected behavior

Tables should be loaded

### Actual behavior

An error shows stating `Could not load shared views. Resource not found.` and no table is loaded.

### Tables app version

0.6.0

### Browser

Firefox 118

### Operating system

Debian 10

### Web server

Nginx

### PHP engine version

PHP 8.2

### Database

MariaDB

**Comment by JensUweB** [comment]
Can confirm. Upgrading from a previous Version to v0.6.0 you get the described Error when opening a already existing table.
But after a few minutes the error resolved itself.
Maybe some upgrade process was running in the background without telling the user.

**Comment by alphasixtyfive** [comment]
> Can confirm. Upgrading from a previous Version to v0.6.0 you get the described Error when opening an already existing table. But after a few minutes the error resolved itself. Maybe some upgrade process was running in the background without telling the user.

Sadly in my case the error persists 18 hrs after an update. Cron job is running fine with no errors.

**Comment by alphasixtyfive** [comment]
Error went away after server reboot. Perhaps restarting memcached or mysql would have also helped.
