### ISSUE TITLE
API Entrypoint copy button get value 'undefined' 

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/tables#582]
### Steps to reproduce

1. Create a table 
2. Open options embedding
3. Click copy icon behind the entrypoint 

### Expected behavior

The entrypoint should be into the clipboard 

### Actual behavior

I get only the value undefined.

![Screenshot_20230917_104559_Chrome](https://github.com/nextcloud/tables/assets/22414212/b3e0534f-bb76-4de1-9523-392a52268a05)

### Tables app version

0.6.0

### Browser

Chrome 117.0

### Client operating system

Android 13

### Operating system

Linux Debian 11

### Web server

Apache

### PHP engine version

None

### Database

MariaDB

**Comment by QazCetelic** [comment]
I'm also experiencing this issue as of 2023-10-18 with version 0.6.0.
