### ISSUE TITLE
Table views: can't filter by column when column type is multiple selection

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/tables#588]
### Steps to reproduce

1. create a column with column type "multiple selection"
2. create a view
3. try to filter the view by the multiple selection column

### Expected behavior

Operators should appear

### Actual behavior

![2023-09-18-175621_392x194_scrot](https://github.com/nextcloud/tables/assets/34077099/8258f570-f4e4-471e-aef7-ede35dd3e515)

### Tables app version

0.6.0

### Browser

Firefox latest

### Client operating system

Arch Linux

### Operating system

Debian 11

### Web server

Nginx

### PHP engine version

PHP 8.2

### Database

MariaDB

### Additional info

All other filters are working fine

**Comment by tbousiou** [comment]
In my case none of the view filters are working, only sorting.

**Comment by tbousiou** [comment]
This bug strangely appears in two of Nextcloud production servers I use, one is Nextcloud 25, PHP 7.4 and the other is Nextcloud 27 with PHP 8.1. And as I said in the previous comment, none of the views filters are working. Strangely, the bug does not appear in my local docker Nextcloud installation with latest version.

**Comment by enjeck** [comment]
fixed at https://github.com/nextcloud/tables/pull/798
