### ISSUE TITLE
Invalid datetime format: 1366 Incorrect string value

### ISSUE THREAD

**Issue by jose1711** [nextcloud/tables#608]
### Steps to reproduce

1. Add Table app to Nextcloud
2. Add example table - Customers

### Expected behavior

New table is created

### Actual behavior

Receive error: "Could not insert table. Unknown error."

### Tables app version

0.6.0

### Browser

Chrome 115

### Client operating system

Linux

### Operating system

Linux

### Web server

Nginx

### PHP engine version

PHP 8.1

### Database

MySQL

### Additional info

The following appears in log:
```
{"reqId":"redacted","level":3,"time":"2023-09-30T23:44:32+00:00","remoteAddr":"redacted","user":"redacted","app":"tables","method":"POST","url":"/index.php/apps/tables/table","message":"An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x92\\xBC' for column `nextcloud`.`oc_tables_tables`.`emoji` at row 1","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36","version":"25.0.0.18","data":{"app":"tables"}}
```

**Comment by juliushaertl** [comment]
Can you check if your database has mb4 support enabled?

https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html
