### ISSUE TITLE
Several display problems with the view filter

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/tables#611]
### Steps to reproduce

![Screenshot 2023-10-05 at 20-05-35 Tabellen - Steffen's Cloud](https://github.com/nextcloud/tables/assets/367592/eb1dc7f9-6a60-4fb7-a255-9ba60c417375)

I try to filter all entries with a date from a specified year.

I thought, I set one filter to "larger than 2023-01-01" and another to "smaller than 2023-12-31".

### Expected behavior

I expected to see just the entries with a date from 2023.

### Actual behavior

See screenshot above:
1. The field in the middle is too small for the German words "ist größer als".
2. The last field seems to be too small for "2023-01-01". 
3. I can't add a date that is larger than today it seems. "2023-12-31" at least is wrong and won't be used as a filter.

### Tables app version

0.6.0

### Browser

Firefox 118.0.1 

### Client operating system

Ubuntu

### Operating system

No sure

### Web server

Apache

### PHP engine version

PHP 8.2

### Database

MariaDB

**Comment by kaffeeringe** [comment]
BTW: how can I help with the translation?

**Comment by tbousiou** [comment]
> BTW: how can I help with the translation?

https://explore.transifex.com/nextcloud/nextcloud/
