### ISSUE TITLE
Can't create a filter for a multi selection field

### ISSUE THREAD

**Issue by schiessle** [nextcloud/tables#648]
### Steps to reproduce

1. Create a table with a "multiple selection" field
2. Create a view and try to set a filter for the field

### Expected behavior

I can set a filter with the two oeprators 
- "equal" filter the exact same selection
-  "contains" filter where the configured value is matched

### Actual behavior

No operator available and therefore I can't set a filter.

tested on c.nc.com

### Tables app version

0.6.0

### Web server

None

### PHP engine version

None

### Database

None

**Comment by schiessle** [comment]
I just notice that there is also no filter on multi select columns possible within a view.

**Comment by enjeck** [comment]
Fixed at https://github.com/nextcloud/tables/pull/798
