### ISSUE TITLE
Display of the number of records

### ISSUE THREAD

**Issue by FriedhelmLG** [nextcloud/tables#725]
### Steps to reproduce

1. There is a table with x records and 2 views
2. Add a data record in the table or in a view.
3. The correct number of data records is now: x+1.
4. In the sidebar, we can now switch back and forth between displaying the table or the views.

### Expected behavior

If a new data record has been successfully saved, the display of the number of existing data records should then be updated.

### Actual behavior

We can see that the number of rows in the sidebar, as well as in the table view, is not updated. If I manually reload the page in the browser, the correct number of rows is displayed.

### Tables app version

0.6.4

### Browser

Firefox 120

### Client operating system

Win10

### Operating system

Linux

### Web server

Apache

### PHP engine version

PHP 8.1

### Database

MariaDB

**Comment by juliushaertl** [comment]
Thanks for reporting, this is already tracked in https://github.com/nextcloud/tables/issues/451
