### ISSUE TITLE
Corrupted tables

### ISSUE THREAD

**Issue by enakhala** [nextcloud/tables#739]
### Steps to reproduce

Not sure if this will recreate the error but this is basically what I did
1. On the web, I created a table and added some raws to it
2. The table was shared with other user
3. The table was exported to CSV 
4. New table was created and the CSV from step 3 was used to create the columns 
5. Both tables worked from awhile until the second table (from step 4) stopped opening and will just show the loading circle  

### Expected behavior

The table that was created using the import feature should work 

### Actual behavior

The table that was created using the import feature stopped opening after a while and will just show the loading circle  

### Tables app version

0.6.5

### Browser

Chrome

### Client operating system

Linux

### Operating system

Linux - Cloudamo

### Web server

None

### PHP engine version

None

### Database

None

**Comment by juliushaertl** [comment]
Can you check the logs and browser console for errors? I would not expect this to be related to the csv export/import but rather some row inserted or edited that caused that which should leave an error trace.

**Comment by enjeck** [comment]
We can reopen later if error is replicated
