### ISSUE TITLE
Smart picker modal select input is too small

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/tables#751]
<img width="637" alt="Screenshot 2023-12-21 at 19 27 45" src="https://github.com/nextcloud/tables/assets/3404133/b9bcb6bb-affc-4a46-8741-37f453d3c607">

Steps to reproduce:
- Open a text file
- Use the smart picker with typing `/table` to insert a table reference to the document

**Comment by juliushaertl** [comment]
@enjeck Maybe you can check that one?

**Comment by enjeck** [comment]
I can't reproduce this. Looks fine for me. 
![Screenshot from 2023-12-29 15-51-26](https://github.com/nextcloud/tables/assets/32180937/f0887069-3ba0-4726-9a2b-c7538c35b859)

**Comment by juliushaertl** [comment]
The issue seems only after you selected something (the active entry shown in the collapsed select input)
