### ISSUE TITLE
Updating rows removes the github url column value

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/tables#777]
### Steps to reproduce

1. have a table with rows and a column for GH URLs
2. update a boolean value from false to true
3. save

### Expected behavior

Data is saved as before but with the changed state/value for the boolean column

### Actual behavior

Boolean change is saved, yet GH url is wiped empty

follow up:
1. open row again for editing
2. read url value
3. save
4. see screenshot
<img width="420" alt="840-292-max" src="https://github.com/nextcloud/tables/assets/1315170/7d30d11e-ff3a-4afa-b351-e98dba1e1f35">

### Tables app version

0.6.5

### Browser

Firefox 121.0.1

### Client operating system

WinPro11

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

c.nc.c - supported apps view (🔎 Hub 7 release missing) -> table (🚒 Supported Apps)

**Comment by juliushaertl** [comment]
<img width="2164" alt="Screenshot 2024-01-16 at 16 14 18" src="https://github.com/nextcloud/tables/assets/3404133/f20f1be9-da80-4bc9-af32-46f90db8d9a3">

**Comment by juliushaertl** [comment]
Could reproduce locally with the db dump of the apps table and the bruteforcesettings app. to be investigated further

**Comment by juliushaertl** [comment]
I noticed that the row content where this happes is:

```
{"title":"https:\/\/github.com\/nextcloud\/external","resourceUrl":"https:\/\/github.com\/nextcloud\/external"}
```

compared to this when adding a new url
```
{"title":"https://github.com/nextcloud/context_chat","subline":"Url","providerId":"url","value":"https://github.com/nextcloud/context_chat"}
```

**Comment by juliushaertl** [comment]
@datenangebot Was there any change with the stored content for a url field?
