### ISSUE TITLE
links are lost during csv-import

### ISSUE THREAD

**Issue by HassoSigbjoernson** [nextcloud/tables#792]
### Steps to reproduce

1. create a table:

| text (type: text) | url (type: link-url)      |
|------------------------|------------------------------|
| text                      | http://example.com |

2. export as csv
3. import csv

### Expected behavior

The complete row should be imported.

| text (type: text) | url (type: link-url)      |
|------------------------|------------------------------|
| text                      | http://example.com |
| text                      | http://example.com |

### Actual behavior

The importer doesn't report any problems, but the url is missing.

| text (type: text) | url (type: link-url)      |
|------------------------|------------------------------|
| text                      | http://example.com |
| text                      |                                     |

### Tables app version

0.6.5

### Database

PostgreSQL

### Additional info

I get the following error message in the Nextcloud log:

`Link cell value has incomplete json string.`

**Comment by juliushaertl** [comment]
This is likely fixed by https://github.com/nextcloud/tables/pull/779

Could you check if the new 0.6.6 release fixes the issue for you?
