### ISSUE TITLE
FR: Add View Filter to Compare Two or More Columns 

### ISSUE THREAD

**Issue by 000Shimmy** [nextcloud/tables#801]
### Is your feature request related to a problem? Please describe.

No, just an enhancement request.

### Describe the solution you'd like

I want to be able to compare the values between columns vs just against a known value.
Ex. Two numeric columns one is "Amount" and the "Paid" 
[Paid] [Lower Than] [Amount]
Which would tell me what rows are still "Owed"
Bonus: if the comparison could also be represented in a the view "Status Bar" as an option. 

### Describe alternatives you've considered

None, except to continue using spreadsheets.

**Comment by juliushaertl** [comment]
Thanks for your suggestion, this is one part of https://github.com/nextcloud/tables/issues/181 so I'd close this as a duplicate.
