### ISSUE TITLE
RFC: DB Structure for Contexts

### ISSUE THREAD

**Issue by blizzz** [nextcloud/tables#812]
For #311, RC

## Structure

```mermaid
---
title: Tables Contexts Database Structure
---
erDiagram

Context ||--o{ Page : contains
Page ||--o{ Page_Content : contains
Context }|--o{ Rel_Context_Resource : contains
Page_Content }o--o{ Rel_Context_Resource : refs
Context ||--o{ Shares : has
Shares ||--o{ Navigation : has

Context {
    int id PK
    string name
    string icon "Material Design Icon URI"
    text description
    string owner_id
    string owner_type "currently only user, group envisioned in a future version"
}

Rel_Context_Resource {
    int id PK
    int context_id 
    int resource_id
    string resource_type
    int permissions "bitmask"
}

Page {
    int id PK
    int context_id
    string page_type "currently start page, or regular (better naming needed)"
}

Page_Content {
    int id PK
    int page_id
    int resource_rel_id
    int order "to be displayed in ascending order"
}

Shares {
    string node_type "introducing context as type"
}

Navigation {
    int share_id PK
    int display_mode "0 - hide, 1 - recipients, 2 - everybody"
    string user_id PK "NULL for default, an entry with user id acts as override"
}
```

### Resource Mapping

Currently, resources can be Tables or Views. In several places we have the tuple of `resource_id`  and `resource_type`.  These could be places in a another tables `Resources` that would contain the `id`, `type` and `original` id. Then, instead of the tuple, we can just refer to the id. This results in another join however, where necessary.

:heavy_check_mark: applied

### Less Normalization

With the current approach each proposed table has its narrow scope and any duplication is avoided. However, it requires joins in most places to map the required entity with the necessary context (pun not intended). It is possible to combine some tables to avoid joining. One candidate would be `Page` and `Page_Contents`. Then, the page id could not be a primary key anymore is it will be used with every row of content it may have.

The same is an options for `Share` and `Permissions`.

:heavy_multiplication_x: dismissed

## Remarks

- tables are prefixed with `**PREFIX**tables_contexts` (aport of the context context table itself, it will just be `**PREFIX**tables_contexts`)
- We (enjeck, datenangebot and I) discussed a possibility to hide specific table and view IDs from the end user by having a masked/hashed or otherwise disguised ID for resources. `Rel_Context_Resources`actually offers this possibility, by introducing an own id (that would also function as PK, changing the current PK to a unique index). 
- Icon: It is stated to be supposed to be a material design icon. Does it make sense to contain an SVG URI here, or only some sort of identifier?

## Changes to first draft

based on the gathered feedback

- the existing `shares` tables being used, and contexts will have the node_type "context".
- the suggested `Permissions` table is dropped, instead a `permissions`  column is added to `rel_context_resource`. It does not seem reasonable to insert these resources into the `shares` table as we lose some information while carrying information that actually does not apply.
- also `rel_context_resource` received a proper id, functioning as primary key, and so resource mapping is used where applicable
- the `show_in_nav_bar` column was removed from the `Contexts` table and instead is now in a new table called `Navigation`.

**Comment by blizzz** [comment]
ToDos:

* [ ] Check reusing the existing `tables_shares` tables
  * the suggestion here is missing the share initiator.

**Comment by juliushaertl** [comment]
One suggestion, maybe we want to either move the show_in_nav_bar to the shares instead which could be useful for managing this separately. Use case I consider there is that a context owner (the one who designs a no-code app with it) might not necessarily be the user of it and we would just clutter their app menu then. Or having a default in the context scope and an override for the shares?

Otherwise this looks sane. My preference on the options would be the resource mapping, I don't see a problem with additional joins as long as we have proper indices.

**Comment by blizzz** [comment]
> One suggestion, maybe we want to either move the show_in_nav_bar to the shares instead which could be useful for managing this separately. Use case I consider there is that a context owner (the one who designs a no-code app with it) might not necessarily be the user of it and we would just clutter their app menu then. Or having a default in the context scope and an override for the shares?

Valid point! And I agree with you. 

For now, as I understand it, the share of a context may go to multiple users and groups, but does not have individual share options. I'd favor then the "Add menu entry" changed into options "Menu entry for all", "Menu entry for share recipients" (needs better wording), "No menu entry". This will have the setting at just one place, instead of two. 

One step further and it deserves a place in user preferences (might help unclutter nav bar, too?) – though this would rather be the task of the nav bar sorting feature.

**Comment by blizzz** [comment]
@enjeck and @juliushaertl thanks for the past discussions and your feedback. I incorporated them and updated the draft accordingly. The changes are also noted down in another section in the description ^

**Comment by blizzz** [comment]
P.S.: On material design, we have a vue library to create them and only the name needs to be fed into it.
