### ISSUE TITLE
Share table view to public without account

### ISSUE THREAD

**Issue by legion986** [nextcloud/tables#814]
### Is your feature request related to a problem? Please describe.

I have a few databases in tables App. Those are library books, fitness exercises, vinyl collection etc. I would like to share the table view to unregistered users. 

### Describe the solution you'd like

There should be an table viewer sub-app to share particular table view without the need of registering a user

### Describe alternatives you've considered

Please write simple PHP script how to connect to API using login, password, nextcloud api link and render table in html

**Comment by juliushaertl** [comment]
Thanks for your proposal, we already have an issue for tracking this in https://github.com/nextcloud/tables/issues/67 so I'll close this one.
