### ISSUE TITLE
Negative dates (before jesus christ) become positive dates

### ISSUE THREAD

**Issue by Atn-D** [nextcloud/tables#824]
### Steps to reproduce

1.Create a date field
2.Fill it in with a negative date, for example `-830/12/31`
3.save

### Expected behavior

Save the date as `-830/12/31`

### Actual behavior

The date is saved at `830/12/31`

### Tables app version

0.6.6

### Browser

all

### Client operating system

all

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

hetzner storage-share

**Comment by enjeck** [comment]
The [NcDateTimePickerNative](https://github.com/nextcloud/tables/pull/647/commits/693ed907223793a53953636ed7c92bb7238ccf64) doesn't support negative dates. I don't think this issue is in scope anymore @juliushaertl
