### ISSUE TITLE
Import: Allow changing row format during import

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/tables#837]
Files being imported may have various data formats while https://github.com/nextcloud/tables/issues/838 might help in some cases we will need to handle customizing the mapping of imports

We should have an intermediate step in the import modal to preview and adjust the import data mapping to the tables structure.

- For each import data column we show some example data
- For each import data column users can select to map it to an existing tables column or create a new one with a selected type

**Comment by enjeck** [comment]
Related: https://github.com/nextcloud/tables/issues/485
