### ISSUE TITLE
Choose left, right or center alignment

### ISSUE THREAD

**Issue by quentinDupont** [nextcloud/tables#858]
### Is your feature request related to a problem? Please describe.

Readability is not good with date field that are right aligned creating huge white space and tight field
![image](https://github.com/nextcloud/tables/assets/9005817/61ec2758-361d-4f4f-8338-557cb6a1a7b5)

### Describe the solution you'd like

As an extra option for column, choose alignment (left, center, right) 

Thanks for all the work !

**Comment by quentinDupont** [comment]
![image](https://github.com/nextcloud/tables/assets/9005817/72fc6902-124c-4119-a599-9004a1f9f6d4)
With other view, it is also not very nice : fields seems not to be related to header name

**Comment by enjeck** [comment]
This is related to https://github.com/nextcloud/tables/issues/360, where we are considering various formatting options. We can just track this there instead.

**Comment by quentinDupont** [comment]
> This is related to #360, where we are considering various formatting options. We can just track this there instead.

good idea, thanks !
