### ISSUE TITLE
Use material design icon for "Reset local adjustments"

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/tables#884]
### Is your feature request related to a problem? Please describe.

![Bildschirmfoto vom 2024-02-29 09-52-49](https://github.com/nextcloud/tables/assets/1374172/22b717a5-1e81-48ab-ae2b-bbd748bfa2db)

### Describe the solution you'd like

Use an arrow left icon from material design

**Comment by juliushaertl** [comment]
Possible options:
- https://pictogrammers.com/library/mdi/icon/filter-remove/ (already used in talk for reset of filtering, so probably the best here)
- https://pictogrammers.com/library/mdi/icon/restore/
- https://pictogrammers.com/library/mdi/icon/close/
