### ISSUE TITLE
Add views, sorting and filters to the tables app for Android

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#922]
Please, consider adding `views` functionality, `sorting` and `filters` to the Android app of the NC Tables.
This will significantly improve UX of using the app on a mobile device. 
Currently, it is very limited and is more like as a prove of concept.

**Comment by juliushaertl** [comment]
This repo is just for the Nextcloud app itself. Please file this feature request in the android app repo at https://github.com/stefan-niedermann/nextcloud-tables
