### ISSUE TITLE
Inserting row should lead to the reload of existing rows in a view

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#923]
### Steps to reproduce

1. Create a table with columns
2. Create a view
3. Add some rows to the view
4. Observe, that the rows are not appearing in the view immediately after adding them, so you need to update the content in the browser manually to view the newly added rows

### Expected behavior

Rows should appear automatically just after adding it in a view

### Actual behavior

The rows do nor appear after clicking the submit button

### Tables app version

0.6.6

### Browser

Brave Version 1.59.120 Chromium: 118.0.5993.88 (Official Build) (64-bit)

### Client operating system

Windows 10 x64

### Operating system

Ubuntu 22.04

### Web server

Apache

### PHP engine version

PHP 8.2

### Database

None

**Comment by enjeck** [comment]
I checked, and this should be fixed on the newer Tables version.

**Comment by ostasevych** [comment]
> I checked, and this should be fixed on the latest Tables version.

Do you mean in upcoming 0.7.0?

**Comment by enjeck** [comment]
@ostasevych Yeah. I tested on 0.7.0-beta.3
