### ISSUE TITLE
selection 字段提交到数据库时是不是应该递交值，而不是ID。

### ISSUE THREAD

**Issue by yufeibiao** [nextcloud/tables#973]
### Is your feature request related to a problem? Please describe.

在表创建时，指定了selection类型的字段选项。插入数据后，如果修改selection字段的选项时，表格将显示错误。同时在“analytics”app中分析时，也不能对selection字段进行分许。

**Comment by enjeck** [comment]
@yufeibiao Please use English

**Comment by juliushaertl** [comment]
As mentioned, please file issue reports in English
