### ISSUE TITLE
Convert column types where possible

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#983]
### Is your feature request related to a problem? Please describe.

I found the need to convert a field type from a single row to textarea for more information can be added and shown as a text field,

### Describe the solution you'd like

Add the conversion of fields to different types if possible, eg
- single text row / textarea
- numeric value / single text row
- options / textarea

### Describe alternatives you've considered

If the conversion leads to the complete or partial loss of the values, please, warn users about that.

**Comment by enjeck** [comment]
Duplicate of https://github.com/nextcloud/tables/issues/485

**Comment by enjeck** [comment]
Duplicate of https://github.com/nextcloud/tables/issues/485
