### ISSUE TITLE
Export data from the view to CSV

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#985]
### Is your feature request related to a problem? Please describe.

Add the possibility to export the data from a specific view to CSV

### Describe the solution you'd like

Views are one of forms to show filtered data. Please, add the functionality to export them to CSV tables.

**Comment by enjeck** [comment]
@ostasevych I believe we already have this? Or am I misunderstanding your request? 
Please see image below:
![g2](https://github.com/nextcloud/tables/assets/32180937/4c399a6e-9a8a-4018-83b5-f2efeb8596b9)

**Comment by ostasevych** [comment]
Hi! Yes, I've missed that somehow.
