### ISSUE TITLE
Leaving default value qualifies as not filled

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/tables#993]
### Steps to reproduce

1. Create a new column of type numeric, for example "quantity".
2. Set default value to 1.
3. Set required to true
4. Add new row. Leave our field value as default (1).

### Expected behavior

Default value should be acceptable

### Actual behavior

You get an error, saying that you should fill all required fields

### Tables app version

0.6.6

### Browser

Firefox 124.0.2

### Client operating system

Any

### Operating system

Ubuntu 22.04

### Web server

Apache

### PHP engine version

PHP 8.1

### Database

PostgreSQL

**Comment by blizzz** [comment]
Could you retry with 0.7.1 please?

**Comment by RTechSn** [comment]
> Could you retry with 0.7.1 please?

Can confirm on 0.7.1. Now a warning appears.
![image](https://github.com/nextcloud/tables/assets/119056784/df6f4314-4485-403d-a98c-35ceb07cdd13)

**Comment by blizzz** [comment]
@enjeck could you check that, if you have time?

**Comment by enjeck** [comment]
This affects other column types too
